branches:
  only:
    - node-pre-gyp
    - pre-gyp-32-bit
    - /^[0-9]/

language: cpp

sudo: false

addons:
  apt:
    packages:
      - build-essential
      - libudev-dev
      - g++-4.8
      - g++-4.8-multilib
      - gcc-multilib

env:
  matrix:
  - NODE_VERSION="0.12" ARCH="ia32"
  - NODE_VERSION="0.12" ARCH="x64"
  - NODE_VERSION="4" ARCH="ia32"
  - NODE_VERSION="4" ARCH="x64"
  - NODE_VERSION="5" ARCH="ia32"
  - NODE_VERSION="5" ARCH="x64"
  - NODE_VERSION="6" ARCH="ia32"
  - NODE_VERSION="6" ARCH="x64"

before_install:
  - export NVM_DIR=~/.nvm
  - . $HOME/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - node --version
  - npm --version

install:
- export PATH=./node_modules/.bin/:$PATH
- npm install -g node-pre-gyp-github

script:
- npm install --build-from-source --node-gyp=$(which pangyp) --arch=$ARCH
- "./node_modules/.bin/node-pre-gyp --target_arch=$ARCH package"
- echo $TRAVIS_TAG
- >
    ([[ "$TRAVIS_TAG" =~ ^[0-9] ]] &&
    node-pre-gyp-github publish) || true
